/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "shapeshift-examples-kotlin"
include(":transformer-mapping")
include(":advanced-mapping")
include(":simple-mapping")
include(":spring-mapping")