version: 2.1
orbs:
  ktlint: idanelh/ktlint@1.0.1
executors:
  jdk8:
    docker:
      - image: cimg/openjdk:8.0
commands:
  run_gradle:
    parameters:
      gradlew_binary:
        type: string
        default: ./gradlew
      tasks:
        description: Gradle tasks to run
        type: string
        default: NONE
    steps:
      - run:
          name: Run Gradle
          command: |
            << parameters.gradlew_binary >> \
              --info \
              --stacktrace \
              --console=plain \
              --no-daemon \
              << parameters.tasks >>
jobs:
  test:
    executor: jdk8
    steps:
      - checkout
      - run_gradle:
          tasks: clean test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t ${CODECOV_TOKEN}
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  version: 2
  build:
    jobs:
      - test
      - ktlint/lint:
          name: lint_shapeshift
          working-directory: shapeshift
      - ktlint/lint:
          name: lint_shapeshift_spring_boot_starter
          working-directory: spring-boot-starter-shapeshift
