/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.krud.shapeshift.examples.kotlin.common-conventions")
    application
}

description = "transformer-mapping"

application {
    mainClass.set("dev.krud.shapeshift.examples.kotlin.MainKt")
}